### ISSUE TITLE
Create an onboarding page to store user information in Firebase

### ISSUE THREAD

**Issue by wellsfletcher** [wellsfletcher/GTStudyBuddy#1]
Collect information like the following:
- Name
- 1st College Semester
- CRNs (and the associated term)
- Phone Number
- Student Organizations?

**Comment by Mohamed-Jelloul** [comment]
Done with most of the work, what's left is how to get a starting term string from the starting term id and where to access the information form from (waiting on the login/signup screen split pull request), submitting later today

**Comment by wellsfletcher** [comment]
Awesome job @Mohamed-Jelloul! You've implemented a huge feature. I'm going close this issue and create a couple new ones for moving the onboarding page and fixing the CRN stuff
