### ISSUE TITLE
Seperating contribution guidlines and README

### ISSUE THREAD

**Issue by alexandrehassan** [wellsfletcher/GTStudyBuddy#39]
The README is mostly set up instructions and contribution guidelines and doesn't explain what the repo is for or the goal of the project. A [contribution.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file) file allows contribution guidelines and instructions to be placed in a standard location and be easily accessible.

**Comment by wellsfletcher** [comment]
I added a description of the project to the README + repo. I'm gonna say that's good enough
